### ISSUE TITLE
PWM_SLICE not working properly

### ISSUE THREAD

**Issue by cristianaprecup** [UPB-FILS-MA/questions#15]
# Question

PWM_SLICE1 is configured for pin2 and pin3:
https://github.com/embassy-rs/embassy/blob/a7eb9bced1daa6e5f9bdf2c888d5920e33786b0b/embassy-rp/src/pwm.rs#L370-L371 ,
but cannot be used in the same time.

![image](https://github.com/UPB-FILS-MA/questions/assets/121363102/fb8e5f65-54c4-4356-b9ff-401a5cb593be)

This is an issue because it reduces the number of pins available.

## Material read
https://github.com/embassy-rs/embassy/blob/a7eb9bced1daa6e5f9bdf2c888d5920e33786b0b/embassy-rp/src/pwm.rs

**Comment by alexandruradovici** [comment]
The problem is that the `Pwm::new_output_a` function takes ownership of the `peripherals.PWM_SLICE1`. This is done to prevent using the same PWM Slice with two different `Pwm` drivers. 

Looking at the documentation of the `Pwm` driver, you can see a `Pwm::new_output_ab` function that takes two pins. The `PwmConfig` structure is only one, as it contains the `compare_a` and `compare_b` values. This means that it controls both of the channels by setting the corresponding value.

In your case, instead of having `pwm_blue` and `pwm_green`, you can use one single `Pwm` driver `pwm_blue_green`. You can control each of the channels by updating `comapre_a` and `compare_b` in the `PwmConfig` structure and calling the `set_config` function of the `Pwm` driver.

**Comment by cristianaprecup** [comment]
Now it's working as expected, thank you.


This is the implementation using `Pwm::new_output_ab` function:
```rs
let mut pwm_blue_green = Pwm::new_output_ab(peripherals.PWM_SLICE1, peripherals.PIN_2, peripherals.PIN_3, config_blue_green.clone());
```

**Comment by mihaiprodann** [comment]
Hi,
As I see in the source file (https://github.com/embassy-rs/embassy/blob/a7eb9bced1daa6e5f9bdf2c888d5920e33786b0b/embassy-rp/src/pwm.rs#L370-L371), there are 4 pins that are using SLICE1, but I can't find any proper function that takes usage of 3 or all 4 of them.
Is there anything that I'm missing?
E.g.
```rs
let mut pwm_blue_green = Pwm::new_output_ab(peripherals.PWM_SLICE1, peripherals.PIN_2, peripherals.PIN_3, config_blue_green.clone());
let mut pwm_blue_green2 = Pwm::new_output_ab(peripherals.PWM_SLICE1, peripherals.PIN_18, peripherals.PIN_19, config_blue_green.clone());
 ```
 Will return the same error. Thank you!

**Comment by alexandruradovici** [comment]
Each PWM slice has two channels and each channel can be mapped to one pin at a time.

**Comment by mihaiprodann** [comment]
I'm not sure I completely understand this. Could you, please, show how this should be implemented in the case of my code?

**Comment by alexandruradovici** [comment]
You cannot use four pins with one PWM slice. You can use a maximum of two pins.

If you need four PWM pins, you have to use two PWM slices.

**Comment by mihaiprodann** [comment]
It is clear now, thank you!
